spring:
  datasource:
    url: jdbc:mysql://api.fittner.co.kr:9615/health?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: health
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: none
        format_sql: true
        show_sql: true
---
spring.config.activate.on-profile: local
spring:
  datasource:
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate
        format_sql: true
        show_sql: true
