spring.profiles.include:
    - database
    - redis
management:
    endpoints:
        web:
            exposure:
                include: "*"
springdoc:
    override-with-generic-response: false
jwt:
    secret-key: ${JWT_SECRET_KEY}
swagger:
    cors-url: ${SWAGGER_CORS_URL}
file:
    uploadPath: ${FILE_UPLOAD_PATH}
    signUploadPath: ${FILE_SIGN_UPLOAD_PATH}
    url: ${FILE_URL}
    aes-key: ${FILE_AES_KEY}
#server:
   #shutdown: graceful
spring:
    lifecycle:
        timeout-per-shutdown-phase: 5s
    servlet:
         multipart:
             max-file-size: 10MB
             max-request-size: 10MB

---
spring.config.activate.on-profile: local
server:
    port: 8080
    shutdown: graceful
spring:
    lifecycle:
        timeout-per-shutdown-phase: 5s
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

jwt:
    secret-key: ${JWT_SECRET_KEY}
swagger:
    cors-url: ${SWAGGER_CORS_URL}
file:
    uploadPath: ${FILE_UPLOAD_PATH}
    signUploadPath: ${FILE_SIGN_UPLOAD_PATH}
    url: ${FILE_URL}
    aes-key: ${FILE_AES_KEY}
aes:
    secret-key: ${AES_SECRET_KEY}
