spring.profiles.include:
    - database
    - redis
management:
    endpoints:
        web:
            exposure:
                include: "*"
springdoc:
    override-with-generic-response: false
jwt:
    secret-key: ${JWT_SECRET_KEY}
swagger:
    cors-url: ${SWAGGER_CORS_URL}
file:
    uploadPath: ${FILE_UPLOAD_PATH}
    url: ${FILE_URL}
#server:
#   port: 8080
#   shutdown: graceful
#spring:
#    lifecycle:
#        timeout-per-shutdown-phase: 5s


---
spring.config.activate.on-profile: local
server:
    port: 8080
    shutdown: graceful
spring:
    lifecycle:
        timeout-per-shutdown-phase: 5s
jwt:
    secret-key: ${JWT_SECRET_KEY}
swagger:
    cors-url: ${SWAGGER_CORS_URL}
file:
    uploadPath: ${FILE_UPLOAD_PATH}
    url: ${FILE_URL}
