### 트레이너가 지정한 센터 리스트 조회
GET http://localhost:8080/api/v1/user/main/centers
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### 메인페이지 일정 간략보기 데이터 조회 API
GET http://localhost:8080/api/v1/user/main/short-schedules?reservationStartDate=20250101&reservationEndDate=20250110
Content-Type: application/json
Authorization: Bearer {{auth_token}}