### 정상 회원가입
POST http://localhost:8080/api/v1/user/join
Content-Type: application/json

{
  "trainerPhone": "01012345678",
  "trainerName": "홍길동",
  "trainerEmail": "newy12@naverd.com",
  "trainerSnsKind": "KAKAO",
  "trainerCiNo": "",
  "trainerFcmToken": "",
  "centerId": "1"
}



### 트레이너가 지정한 센터 리스트 조회
GET http://localhost:8080/api/v1/user/centers
Content-Type: application/json
Authorization: Bearer {{auth_token}}




