spring:
  data:
    redis:
      host: api.fittner.co.kr
      port: 1525
      password: ${REDIS_PASSWORD}

---
spring.config.activate.on-profile: local
spring:
  data:
    redis:
      password: ${REDIS_PASSWORD}
